a= input('digite algo')
print ('o tipo primitivo desse valor e',type(a))
print('so tem espacos?',a.isspace())
print('é um numero?',a.isnumeric())
print('sao letras',a.isalpha())
print('esta em maisculas',a.isupper())
print('esta em minusculas',a.islower())
print('esta capitalizada',a.istitle())
print('é alfanumerico',a.isalnum())